### ISSUE TITLE
Running examples on qemu

### ISSUE THREAD

**Issue by AntonOellerer** [rp-rs/rp-hal#477]
Hey,
To test my program before running it on a pico, I would like to emulate it via qemu.
To make sure this would work, I cloned this repo, and set
 `runner = "qemu-system-arm -cpu cortex-m0 -machine lm3s6965evb -nographic -semihosting-config enable=on,target=native -kernel"` in the `.cargo/config`.
When executing `cargo run --example pico_blinky` in the `boards/rp-pico` directory, the following issue occurs:
```
Timer with period zero, disabling
qemu: fatal: Lockup: can't escalate 3 to HardFault (current priority -1)

R00=00000000 R01=00000000 R02=00000000 R03=00000000
R04=00000000 R05=00000000 R06=00000000 R07=00000000
R08=00000000 R09=00000000 R10=00000000 R11=00000000
R12=00000000 R13=ffffffe0 R14=fffffff9 R15=00000000
XPSR=40000003 -Z-- A handler
FPSCR: 00000000
Aborted (core dumped)
```

If I try user mode emulation (setting `runner = "qemu-arm -cpu cortex-m0"`), I get the following message:
```
qemu-arm: /home/antono/Nextcloud/Uni/Masterarbeit/existing_projects/rp-hal/target/thumbv6m-none-eabi/debug/examples/pico_blinky: Error mapping file: Invalid argument
```
I solved this by commenting out the `"-C", "link-arg=--nmagic"` line in the `rustflags`, but now I just get a segfault (with `-strace`):
```
--- SIGSEGV {si_signo=SIGSEGV, si_code=1, si_addr=0xd0000100} ---
Segmentation fault (core dumped)
```

The core dump looks like this:
```coredump
Reading symbols from /home/user/rp-hal/target/thumbv6m-none-eabi/debug/examples/pico_blinky...
[New LWP 908451]
Core was generated by `/home/user/existing_projects/rp-hal/target/thumbv6'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  core::ptr::write_volatile<u32> (dst=0xd0000100, src=1) at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/ptr/mod.rs:1543
1543    /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/ptr/mod.rs: No such file or directory.
```

Do you know whether there is some way to make the examples run via qemu?
Best regards
Anton Oellerer

**Comment by ithinuel** [comment]
Hi, I thougt I'd replied to your issue much earlier.

As far I am aware, qemu does not implement support for the rp2040 chip and related boards.
So it is expected that your example does not run on Qemu. Also, you are passing `-machine lm3s6965evb ` where the machine name is for the [lm3s696](https://www.ti.com/product/LM3S6965) TI based evaluation board. You'd expect something along `-machine rp-pico` or some other board name.

There might be some support for cortex-m0 based target but I've never tried it.

I am closing this issue because it is not really something we can solve with the code in this repository.
