### ISSUE TITLE
rp2040-e5 feature can randomly panic if not using gpio::Pins

### ISSUE THREAD

**Issue by dlkj** [rp-rs/rp-hal#606]
# Reproduction:

* Enable the `rp2040-e5` feature
* Use `usb::UsbBus`
* Don't use `gpio::Pins`

After power-on, usb operations may panic with:

```
ERROR panicked at 'IO Bank 0 must be out of reset for this work around to function properly.', rp2040-hal-0.8.1\src\usb\errata5.rs:36:21
```

# Workaround

Initialise `gpio::Pins`

```rust
    let sio = hal::sio::Sio::new(pac.SIO);
    let _pins = hal::gpio::Pins::new(
        pac.IO_BANK0,
        pac.PADS_BANK0,
        sio.gpio_bank0,
        &mut pac.RESETS,
    );
```

**Comment by ithinuel** [comment]
Because the errata-5 workaround takes (steals) control over gpio15 for the duration of the reset's workaround, the bank0 needs to be out of its reset state.
That is an expected panic (via an assert).

https://github.com/rp-rs/rp-hal/pull/607 is a proposed improvement to the documentation to make this a bit less surprising.
