### ISSUE TITLE
Mention rustflags/memory.x in README

### ISSUE THREAD

**Issue by Supreeeme** [rp-rs/rp-hal#669]
While getting started with this crate I was trying to figure out why elf2uf2-rs wouldn't work for me, until I found #307. I don't think it's immediately clear from the README that not using the template will result in #307, so it would be useful to point out what exactly from the template is needed (rustflags/memory.x) to get a minimum working project if one should choose to forego the template app.

**Comment by jannic** [comment]
Very good point. Even the [Embedded Rust Book](https://docs.rust-embedded.org/book/) doesn't explain the necessary linker argument.

I'm not sure how many details we should add to the README, because it's already quite long. But we should mention the requirement and add a link to some more detailed explanation. The best explanation I know is at https://docs.rs/cortex-m-rt/0.7.3/cortex_m_rt/, but it adds the linker argument to the command line manually. That's of course a valid way to do it, but not what most people would do in practice.
