### ISSUE TITLE
Readme seems to use wrong cargo run command

### ISSUE THREAD

**Issue by ZachariasFrings** [rp-rs/rp-hal#806]
Good Evening Everyone,

I was just wondering about a difference in the readme and when actually trying to cargo run a example from this repo.

In the readme it is stated that you should use `cargo run --release --example <example>`.

But most of the time the examples require a certain feature to be passed to them when they are being run.

This results in the actual command being: `cargo run --release --features="<specific-feature>" --example <example>`

Why is that, and shouldnt this be changed in the readme, or am I reading things wrong?

**Comment by 9names** [comment]
rp2040-hal is a lib crate. Where possible, we want to not enable features by default, because that makes it trickier for end-users to use this crate 
The examples, however, have to have these features enabled. You can see that we specify which features are required in the cargo.toml.
https://github.com/rp-rs/rp-hal/blob/d15284402c80d9cc564e5bf1a7e2db2c43be02b1/rp2040-hal/Cargo.toml#L183

A PR to update the docs on how to run the examples, with a "--features" arg that enables all the features required to run most/all examples would be welcome.
